name: 'Install Dependencies'
description: 'Sets up common tools and dependencies used across workflows'
inputs:
  cleanup-runner:
    description: 'Run initial cleanup of runner'
    required: false
    default: 'false'
  install-just:
    description: 'Install Just task runner'
    required: false
    default: 'true'
  install-uv:
    description: 'Install uv package manager'
    required: false
    default: 'true'
  just-version:
    description: 'Version of Just to install'
    required: false
    default: '1.43.1'
  uv-cache-dependency-glob:
    description: 'Glob pattern for uv cache dependency files'
    required: false
    default: ''
  uv-version:
    description: 'Version of uv to install'
    required: false
    default: '0.9.7'

runs:
  using: 'composite'
  steps:
    - name: Initial cleanup
      if: ${{ inputs.cleanup-runner == 'true' }}
      uses: ./.github/actions/cleanup-runner
      with:
        type: "initial"

    - name: Install Just
      if: ${{ inputs.install-just == 'true' }}
      uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0
      with:
        just-version: ${{ inputs.just-version }}

    - name: Install uv
      if: ${{ inputs.install-uv == 'true' }}
      uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: ${{ inputs.uv-cache-dependency-glob != '' && 'true' || 'false' }}
        cache-dependency-glob: ${{ inputs.uv-cache-dependency-glob }}
