# Platform services
library:
  - library/**
  - .github/workflows/**

backend:
  - application/backend/**
  - library/**  # Backend might depend on library changes
  - .github/workflows/**
ui:
  - application/ui/**
  - .github/workflows/**

distrib:
  - application/docker/**
