# Platform services
library:
  - library/**
  - .github/workflows/**

backend:
  - application/backend/**
  - library/**  # Backend might depend on library changes
  - .github/workflows/**
ui:
  - application/ui/**
  - .github/workflows/**
  - application/backend/app/domain/services/schemas/**
  - application/backend/app/api/**

distrib:
  - application/**
  - library/**
  - .github/workflows/**
