name: 'Cleanup Runner Resources'
description: 'Free up disk space and clean Docker resources on GitHub Actions runner'

inputs:
  type:
    description: 'Type of cleanup to perform: initial or pre-build'
    required: true
    default: 'initial'

runs:
  using: 'composite'
  steps:
    - name: Show initial resources
      shell: bash
      run: |
        echo "=== Initial System Resources ==="
        df -h
        free -h
        docker system df 2>/dev/null || echo "Docker not available yet"
        echo ""

    - name: System cleanup
      if: inputs.type == 'initial'
      shell: bash
      run: |
        echo "=== Performing System Cleanup ==="

        # Remove large directories in parallel for speed
        # Each & backgrounds the process, wait at the end synchronizes them all
        sudo rm -rf /usr/share/dotnet &
        sudo rm -rf /usr/local/lib/android &
        sudo rm -rf /opt/ghc &
        sudo rm -rf /usr/local/share/boost &
        sudo rm -rf /opt/hostedtoolcache &

        # Quick cleanup of apt cache (fast operation, run in parallel)
        sudo apt-get clean &

        # Wait for all background processes to complete
        wait

        echo "Cleanup complete"

    - name: Pre-build cleanup
      if: inputs.type == 'pre-build'
      shell: bash
      run: |
        echo "=== Performing Pre-build Cleanup ==="
        docker system prune -a -f --volumes || true
        docker builder prune -a -f || true

        echo "Cleaning temporary files..."
        sudo rm -rf /tmp/* || true
        sudo rm -rf /var/tmp/* || true

    - name: Show final resources
      shell: bash
      run: |
        echo "=== Post-cleanup System Resources ==="
        df -h
        free -h
        docker system df 2>/dev/null || echo "Docker not available"
        echo ""
